{
 "title": "Consul Connect Service",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(envoy_http_rq_total, local_cluster)"
   },
   {
    "name": "inbound",
    "query": "label_values(envoy_cluster_upstream_rq_completed{cluster_name=\"$service\"}, local_cluster)"
   },
   {
    "name": "outbound",
    "query": "label_values(envoy_cluster_external_upstream_rq_completed{local_cluster=\"$service\"}, cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2.4, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;\n  <span style=\"font-size: 32px\">svc/$service</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2.4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{response_code_class!=\"5\",local_cluster=\"$service\",http_conn_manager_prefix=\"public_listener_http\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx{local_cluster=\"$service\",http_conn_manager_prefix=\"public_listener_http\"}[1m]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{local_cluster=\"$service\",http_conn_manager_prefix=\"public_listener_http\"}[30s]))"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2.4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(envoy_cluster_upstream_rq_time_bucket{cluster_name=\"$service\"}[30s])) by (le))",
     "legendFormat": "Source: $local_cluster"
    }
   ]
  },
  {
   "title": "Data Rx",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2.4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total[1m]))*8 + sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{local_cluster=\"$service\"}[1m])) * 8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Data Tx",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2.4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total[1m]))*8 + sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{local_cluster=\"$service\"}[1m])) * 8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 7.4 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "RESPONSES PER MIN BY HTTP STATUS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9.600000000000001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{local_cluster=\"$service\",http_conn_manager_prefix=\"public_listener_http\"}[1m])) by (local_cluster, response_code_class)",
     "legendFormat": "{{response_code_class}}xx"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9.600000000000001 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{local_cluster=\"$service\",http_conn_manager_prefix=\"public_listener_http\"}[30s]))",
     "legendFormat": "🔒svc/{{dst_service}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9.600000000000001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(envoy_cluster_upstream_rq_time_bucket{cluster_name=\"$service\"}[30s])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(envoy_cluster_upstream_rq_time_bucket{cluster_name=\"$service\"}[30s])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_cluster_upstream_rq_time_bucket{cluster_name=\"$service\"}[30s])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 16.6 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY SOURCE</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18.8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{response_code_class!=\"5\",cluster_name=\"$service\"}[30s])) by (cluster_name, local_cluster) / sum(irate(envoy_cluster_upstream_rq_xx{cluster_name=\"$service\"}[30s])) by (cluster_name, local_cluster)",
     "legendFormat": "source:{{local_cluster}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18.8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{cluster_name=\"$service\"}[30s])) by (cluster_name, local_cluster)",
     "legendFormat": "src: {{local_cluster}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18.8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_name=\"$service\"}[30s])) by (le, cluster_name, local_cluster))",
     "legendFormat": "src: {{local_cluster}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 25.8 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC BY UPSTREAM</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{response_code_class!=\"5\",local_cluster=\"$service\",cluster_name!~\"local_.*\"}[30s])) by (local_cluster, cluster_name) / sum(irate(envoy_cluster_upstream_rq_xx{local_cluster=\"$service\",cluster_name!~\"local_.*\"}[30s])) by (local_cluster, cluster_name)",
     "legendFormat": "upstream: {{cluster_name}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{local_cluster=\"$service\",cluster_name!~\"local_.*\"}[30s])) by (local_cluster, cluster_name)",
     "legendFormat": "upstream: {{cluster_name}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{local_cluster=\"$service\",cluster_name!~\"local_.*\"}[30s])) by (le, local_cluster, cluster_name))",
     "legendFormat": "upstream: {{cluster_name}}"
    }
   ]
  }
 ]
}