{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\"><img src=\"https://emojify.today/images/emojify_small.png\" alt=\"Consul Icon\"></div>"
  },
  {
   "title": "Requests/s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"upstream_emojify-api_http|upstream_emojify-website_http\",local_cluster=\"emojify-ingress\", envoy_response_code_class=~\"2|4\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"upstream_emojify-api_http|upstream_emojify-website_http\",local_cluster=\"emojify-ingress\", envoy_response_code_class=~\"5\"}[60s]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">svc/emojify-website</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  HTTP requests from the emojify-ingress service to the emojify-website service via the sidecar proxies.\n</div>"
  },
  {
   "title": "Website Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{local_cluster=\"emojify-ingress\",envoy_cluster_name=\"emojify-website\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Website Requests (time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time{envoy_cluster_name=\"emojify-website\"} > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"emojify-website\"}[30s]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"emojify-website\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">svc/emojify-api</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  HTTP requests from the emojify-ingress service to the emojify-api service via the sidecar proxies.\n</div>"
  },
  {
   "title": "API Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "API Requests (time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time{envoy_cluster_name=\"emojify-api\"} > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"emojify-api\"}[30s]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"emojify-api\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">svc/emojify-cache</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  GRPC requests from the emojify-api service to the emojify-cache service via the sidecar proxies.\n</div>"
  },
  {
   "title": "Cache Methods (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_grpc_total[30s])) by (envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "Cache Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{local_cluster=\"emojify-api\",envoy_cluster_name=\"emojify-cache\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  }
 ]
}